apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: dev-ns
subjects:
- kind: ServiceAccount
  name: dev-user       
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

